docs_dir: docs
site_name: PLUME
site_author: Charles JAVERLIAT
copyright: GNU General Public License v3.0
repo_url: https://github.com/liris-xr/PLUME/
repo_name: liris-xr/PLUME
edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
  palette:
    primary: "black"
    accent: "light blue"
  features:
    # - navigation.indexes
    - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    - toc.follow
    - toc.integrate

plugins:
  - search
  - markdown-exec
  - awesome-pages
  - glightbox:
      auto_caption: true
  - macros
  - print-site #always define as last plugin

extra_css:
  - styles/style.css

watch:
  - overrides

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
