docs_dir: docs
site_name: PLUME
site_author: Charles JAVERLIAT
copyright: GNU General Public License v3.0
repo_url: https://github.com/liris-xr/PLUME/

theme:
  name: material
  logo: images/plume_logo_dark.png
  palette:
    primary: 'black'
    accent: 'light blue'
  features:
    - navigation.indexes
    - navigation.footer
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - awesome-pages

hooks:
  - generate_protos_docs.py

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list