docs_dir: docs
site_name: PLUME
site_author: Charles JAVERLIAT
repo_url: https://github.com/liris-xr/PLUME/
repo_name: liris-xr/PLUME
edit_uri: edit/master/docs/

theme:
  name: material
  custom_dir: overrides
  logo: images/logo.png
  palette:
    primary: "black"
    accent: "light blue"
  features:
    # - navigation.indexes
    # - navigation.expand
    - navigation.sections
    - navigation.footer
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - content.action.edit
    - content.code.copy
    - content.code.annotate
    # - toc.integrate

plugins:
  - search
  - markdown-exec
  - awesome-pages
  - glightbox:
      auto_caption: true
  - macros
  - print-site #always define as last plugin

extra:
  analytics:
    provider: google
    property: G-D7DXE73VVW
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to collect your feedback on the tutorial pages, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

copyright: >
  GNU General Public License v3.0<br>
  <a href="#__consent">Change cookie settings</a>

extra_css:
  - styles/style.css

watch:
  - overrides

markdown_extensions:
  - abbr
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - attr_list
